### ISSUE TITLE
Namespace WebKit not available / No module found pArAnoIA

### ISSUE THREAD

**Issue by Mouradif** [epsylon/paranoia-browser#3]
Hi there,

I have the exact same problem as #1 and I have gir1.2-webkit2-4.0 installed :

```
root@kali:~# apt install gir1.2-webkit2-4.0 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-webkit2-4.0 is already the newest version (2.26.2-1).
0 upgraded, 0 newly installed, 0 to remove and 239 not upgraded.

```
After a successful installation (which by the way also required installation of `libmaxminddb-dev` on Kali 2019.4), I get the two same errors depending if I try
```
$ python pArAnoIA.py
Traceback (most recent call last):
  File "./pArAnoIA.py", line 10, in <module>
    from core.main import Browser
  File "/root/paranoia-browser/core/main.py", line 14, in
    gi.require_version('WebKit', '3.0')
  File "/usr/lib/python2.7/dist-packages/gi/init.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available
```
or
```
$ paranoia
Traceback (most recent call last):
  File "/usr/local/bin/paranoia", line 11, in <module>
    load_entry_point('pArAnoIA==0.1', 'gui_scripts', 'paranoia')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named pArAnoIA
```

What did I miss ?

**Comment by epsylon** [comment]
pArAnoIA-Browser has been ported to Python3.x: https://github.com/epsylon/paranoia-browser/commit/1f8c487c74275d5218ee7d0f03ec5d44ddd734ee
